[package]
name = "rust-notebook"
version = "1.5.10"
authors = ["Jkutkut"]
repository = "https://github.com/Jkutkut/rust-notebook"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.27.0"
