[package]
name = "rust-notebook"
version = "0.2.1"
authors = ["Jkutkut"]
repository = "https://github.com/Jkutkut/rust-notebook"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
