PRAGMA foreign_keys = ON;

CREATE TABLE CATEGORY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CAT_NAME VARCHAR(42) NOT NULL UNIQUE
);

CREATE TABLE TAG (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TAG_NAME VARCHAR(42) UNIQUE
);

CREATE TABLE NOTES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTE_NAME VARCHAR(42) NOT NULL,
    NOTE_DESC VARCHAR(420) NOT NULL,
    
    CATEGORY_ID INT NOT NULL,
    TAG_ID INT NOT NULL,

    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

INSERT INTO CATEGORY (CAT_NAME) VALUES ('UNCATAGORIZED');
INSERT INTO TAG (TAG_NAME) VALUES ('UNTAGGED');

INSERT INTO CATEGORY (CAT_NAME) VALUES ('Ideas');
INSERT INTO CATEGORY (CAT_NAME) VALUES ('42');

INSERT INTO TAG (TAG_NAME) VALUES ('Homework');
INSERT INTO TAG (TAG_NAME) VALUES ('Bug');

INSERT INTO NOTES (NOTE_NAME, NOTE_DESC, CATEGORY_ID, TAG_ID)
VALUES ('Finish project 1', 'Finish and submit project', 3, 1);

INSERT INTO NOTES (NOTE_NAME, NOTE_DESC, CATEGORY_ID, TAG_ID)
VALUES ('Finish project 2', 'Finish and submit project', 3, 1);

INSERT INTO NOTES (NOTE_NAME, NOTE_DESC, CATEGORY_ID, TAG_ID)
VALUES ('General note', 'Note without cat nor tag', 1, 1);

INSERT INTO NOTES (NOTE_NAME, NOTE_DESC, CATEGORY_ID, TAG_ID)
VALUES ('Only tag', 'No category', 1, 2);

INSERT INTO NOTES (NOTE_NAME, NOTE_DESC, CATEGORY_ID, TAG_ID)
VALUES ('Idea 1', 'Idea number 1', 2, 1);

INSERT INTO NOTES (NOTE_NAME, NOTE_DESC, CATEGORY_ID, TAG_ID)
VALUES ('Bug 42', '', 3, 3);
