PRAGMA foreign_keys = ON;

CREATE TABLE CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CAT_NAME VARCHAR(42) NOT NULL UNIQUE
);

CREATE TABLE TAG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TAG_NAME VARCHAR(42) UNIQUE
);

CREATE TABLE NOTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOTE_NAME VARCHAR(42) NOT NULL,
    NOTE_DESC VARCHAR(420) NOT NULL,
    
    CATEGORY_ID INT NOT NULL,
    TAG_ID INT NOT NULL,

    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(ID)
);

INSERT INTO CATEGORY (CAT_NAME) VALUES ('UNCATAGORIZED');
INSERT INTO TAG (TAG_NAME) VALUES ('UNTAGGED');
